### ISSUE TITLE
Memory manager features

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#129]
A list of related issues:
- [X] Make methods of Memory class for copy to and from another objects #76 
- [X] Expose the USM fine-grained control functions `mem_advise` and `prefetch` in the C API #45 
- [X] Expose USM aligned_alloc* functions #43
- [X] Compare USM with RMM #126

**Comment by diptorupd** [comment]
Refer #152

**Comment by oleksandr-pavlyk** [comment]
All of these issue are addressed in #152
