### ISSUE TITLE
Documentation and other improvements

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/dpctl#130]
Documentation:
- [x] README
- [x] #140 Create Sphinx docs
- [x] #137 Examples
- [x] Update changelog file
- [x] #141 Update CONTRIBUTION.md (#91, #272 )
- [x] #140 Generate C++ docs with doxygen

Build system, CI and tools:
- [x] #91 Apply code formatting for Python code with black
- [x] #145 Use setup.py for building C++ backend
- [x] #144 Fix all warnings
- [x] #135 Pass [snyk](https://snyk.io/) checks
- [x] #142 Minimize setyp.py variables
- [x] #272 Apply code formatting for C++ code with clang-format
    - [x] #136 standard C/C++ style
- [x] Code style check ([flake8](https://github.com/pycqa/flake8), [isort](https://github.com/pycqa/isort)) in CI
- [x] #220 Add linting (flake8)
- [ ] Add C/C++ linting - https://clang.llvm.org/extra/clang-tidy/
- [ ] #98 Activate C++ tests in CI
- [x] #221 Enable test coverage
- [x] #237 Enable pre-commit hooks for fast local checks during development
- [ ] Test dpctl on different types of machines
    - [x] with both OpenCL and Level 0 GPU drivers present
    - [x] w/o OpenCL GPU/CPU drivers
    - [x] w/o Level0 GPU drivers
    - [ ] w/o any SYCL drivers
- [x] Snyk - Security vulnerabilities for production code (Python, Java) (Manual)
- [x] Bandit – Static Code analysis for Python code (Pre-commit)
- [x] Klockwork – Static Code analysis for c,c+ code (Manual)

Refactoring:
- [x] #138 Remove OpenCL backend
- [x] #38 #121 Common name style for Cython modules
- [x] #31 Finish renamings
- [x] #35 Improve error handling in C-API.
- [x] #143 Split sycl_core.pyx

**Comment by diptorupd** [comment]
@PokhodenkoSA what will be the benefit of `Use setup.py for building C++ backend`?

**Comment by PokhodenkoSA** [comment]
> @PokhodenkoSA what will be the benefit of `Use setup.py for building C++ backend`?

Answered in #145.

**Comment by diptorupd** [comment]
@oleksandr-pavlyk I think we can close this issue as most of everything has been completed.
