### ISSUE TITLE
Complete the implementation of SYCL device interface

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#285]
There are several gap in dpctl's implementation of SYCL's device class functions as specified in [SYCL 2020 spec](https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf). This ticket is aimed at addressing those gaps:

- [x] Implement wrappers in C API and Python API for all [device descriptor information types](https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf#%5B%7B%22num%22%3A133%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C587.69%2Cnull%5D). We currently have implementations for some of the information types *e.g.*, `DPCTLDevice_GetDriverInfo`, `DPCTLDevice_GetMaxComputeUnits`. #286 
- [x] Fix function names: https://github.com/IntelPython/dpctl/issues/284
- [x] Implement support for sub-devices. #290 SYCL has three `create_sub_devices` functions and we should support all three:
  - [x] `DPCTLDevice_CreateSubDevicesEqually`
  - [x] `DPCTLDevice_CreateSubDevicesByCounts`
  - [x] `DPCTLDevice_CreateSubDevicesByAffinityDomain`
 - [x] Implement `get_backend` (proposed name `DPCTLDevice_GetBackend()`) #291
 - [x] Implement `get_platform`  (proposed name `DPCTLDevice_GetPlatform()`) #291
 - [ ] ~Implement `get_backend_info`  (proposed name `DPCTLDevice_GetBackendInfo()`) #291~
 - [x] Support for aspects #292
   - [x] Add [aspects](https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf#%5B%7B%22num%22%3A2320%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C362.89%2Cnull%5D) as a new enum class  (`DPCTLSyclAspect`) to `dpctl_sycl_enum_types.h`
   - [x] Maybe implemented as `bool DPCTLDevice_Has(DPCTLSyclAspect A)` in C API and `cpdef has(aspect=*)` in Cython?
- [x] Improve the print info functions #293
  - [ ] ~The device print info functions in both C and Python should support printing all info and aspects~.
  - [ ] ~The functions should have a "less" option to limit the amount of descriptors that are printed. By default, the less option should be turned on and only print a limited set of information (maybe restrict to what the functions print currently)~
- [x] Improve the `__repr__` function of `SyclDevice` class. (TBD) #294
- [x] Add docstrings and tests #295
  - [x] Gtest for C-API
  - [x] Pytest for Python API 
- [ ] API documentation
  - [ ] https://github.com/IntelPython/dpctl/issues/233

**Comment by diptorupd** [comment]
Closing as most tasks are complete.
