### ISSUE TITLE
Extend the C-API to support sycl::event

### ISSUE THREAD

**Issue by diptorupd** [IntelPython/dpctl#500]
The issue deals with extending the C-API to support `sycl::event`. The sub-tasks include:

- [x] Add a new function `DPCTLEvent_Copy` to create a copy of a `sycl::event`. Look at existing implementation of `DPCTLQueue_Copy` #504  .
- [x] Add a new function `DPCTLEvent_WaitAndThrow(ERef)` that wraps `sycl::event::wait_and_throw()` #513 
- [x] Add a new function `DPCTLEvent_GetBackend(ERef)` that will return the back end associated with a `sycl::event` #507 .
- [x] Add a new function `DPCTLEvent_GetWaitList(ERef)` to wrap `sycl::event::get_wait_list()` returning a vector of events #510 .
- [x] Add a new function `DPCTLEvent_GetCommandExecutionStatus(ERef)` to wrap ` sycl::event::get_info<sycl::info::event::command_execution_status>()` returning an `enum class event_command_status : int { submitted, running, complete}`. #516 
- [x] Add wrapper functions for : 
  - [x] `sycl::event::get_profiling_info<sycl::info::event_profiling::command_submit>()`
  - [x] `sycl::event::get_profiling_info<sycl::info::event_profiling::command_start>()`
  - [x] `sycl::event::get_profiling_info<sycl::info::event_profiling::command_end>()`
All these functions will return a `uint64_t` value of device timer corresponding to the logged time of referenced operations. These are blocking operations (i.e. wait on the event), and throw `sycl::invalid_object_code` if the queue that created the event did not have profiling enabled. #519

**Comment by oleksandr-pavlyk** [comment]
These were merged to dpctl main branch. Resolving.
